language: generic
sudo: required
dist: trusty

matrix:
  include:
    - env: SCHEME=native
    - env: SCHEME=quilt

install:
  - sudo apt-get update
  - sudo apt-get install cowbuilder debhelper devscripts aria2
  - sudo pip install rosinstall_generator wstool
  - ./update_cowbuilder

script:
  - ./build_package_${SCHEME}
  - sudo cowbuilder --build build/*.dsc
  - ls -lah /var/cache/pbuilder/result/*.deb
